package com.example.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


public class Department {
	
@DynamoDBHashKey(attributeName="deptId")
@DynamoDBAutoGeneratedKey
private String deptId;

@DynamoDBAttribute(attributeName="deptName")
private String deptName;

@DynamoDBAttribute(attributeName="email")
private String location;

public String getDeptId() {
	return deptId;
}

public void setDeptId(String deptId) {
	this.deptId = deptId;
}

public String getDeptName() {
	return deptName;
}

public void setDeptName(String deptName) {
	this.deptName = deptName;
}

public String getLocation() {
	return location;
}

public void setLocation(String location) {
	this.location = location;
}




}
