package com.example.demo.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="employee")
public class Employee {
	
	@DynamoDBHashKey(attributeName="employeeId")
	@DynamoDBAutoGeneratedKey
	private String employeeId;
	
	@DynamoDBRangeKey(attributeName="employeeName")
	private String employeeName;
	
	@DynamoDBAttribute(attributeName="email")
	private String email;
	
	@DynamoDBAttribute(attributeName="contact")
	private String contact;
	
	@DynamoDBAttribute(attributeName="department")
	private Department department;

	
	public String getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
	
	
	
}
